/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.reto5.reto5.vista;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author danie
 */
public class Vista2 extends javax.swing.JFrame {

    /**
     * Creates new form Vista2
     */
    public Vista2() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Actualizarframe = new javax.swing.JFrame();
        actualizarlabel = new javax.swing.JLabel();
        descripcionlabel = new javax.swing.JLabel();
        actnombrelabel = new javax.swing.JLabel();
        actpreciolabel = new javax.swing.JLabel();
        actinventariolabel = new javax.swing.JLabel();
        actboton = new javax.swing.JButton();
        actnombretxt = new javax.swing.JTextField();
        actpreciotxt = new javax.swing.JTextField();
        actinventariotxt = new javax.swing.JTextField();
        bienvenidoinventarioapp = new javax.swing.JLabel();
        agregarproductopanel = new javax.swing.JPanel();
        Labelnombre = new javax.swing.JLabel();
        Labelprecio = new javax.swing.JLabel();
        labelinventario = new javax.swing.JLabel();
        camponombre = new javax.swing.JTextField();
        campoprecio = new javax.swing.JTextField();
        campoinventario = new javax.swing.JTextField();
        botonagregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaproductos = new javax.swing.JTable();
        botonborrar = new javax.swing.JButton();
        botonactualizar1 = new javax.swing.JButton();
        botoninforme = new javax.swing.JButton();

        jButton1.setText("jButton1");

        actualizarlabel.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        actualizarlabel.setText("ACTUALIZAR PRODUCTO");

        descripcionlabel.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        descripcionlabel.setText("Ingrese los datos a actualizar");

        actnombrelabel.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        actnombrelabel.setText("Nombre");

        actpreciolabel.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        actpreciolabel.setText("Precio");

        actinventariolabel.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        actinventariolabel.setText("Inventario");

        actboton.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        actboton.setText("ACTUALIZAR");
        actboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actbotonActionPerformed(evt);
            }
        });

        actnombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actnombretxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ActualizarframeLayout = new javax.swing.GroupLayout(Actualizarframe.getContentPane());
        Actualizarframe.getContentPane().setLayout(ActualizarframeLayout);
        ActualizarframeLayout.setHorizontalGroup(
            ActualizarframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualizarframeLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(ActualizarframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ActualizarframeLayout.createSequentialGroup()
                        .addGroup(ActualizarframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ActualizarframeLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(actualizarlabel))
                            .addGroup(ActualizarframeLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(descripcionlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ActualizarframeLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(actboton)))
                        .addGap(94, 94, 94))
                    .addGroup(ActualizarframeLayout.createSequentialGroup()
                        .addGroup(ActualizarframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actpreciolabel)
                            .addComponent(actnombrelabel)
                            .addComponent(actinventariolabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ActualizarframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(actnombretxt, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(actpreciotxt)
                            .addComponent(actinventariotxt))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        ActualizarframeLayout.setVerticalGroup(
            ActualizarframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualizarframeLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(actualizarlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcionlabel)
                .addGap(18, 18, 18)
                .addGroup(ActualizarframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actnombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actnombrelabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ActualizarframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actpreciolabel)
                    .addComponent(actpreciotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ActualizarframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actinventariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actinventariolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(actboton)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reto 5");

        bienvenidoinventarioapp.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        bienvenidoinventarioapp.setText("Bienvenido a Inventario App");

        agregarproductopanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Agregar Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Tai Le", 1, 12))); // NOI18N

        Labelnombre.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        Labelnombre.setText("Nombre");

        Labelprecio.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        Labelprecio.setText("Precio");

        labelinventario.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        labelinventario.setText("Inventario");

        camponombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camponombreActionPerformed(evt);
            }
        });

        botonagregar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        botonagregar.setText("Agregar");

        javax.swing.GroupLayout agregarproductopanelLayout = new javax.swing.GroupLayout(agregarproductopanel);
        agregarproductopanel.setLayout(agregarproductopanelLayout);
        agregarproductopanelLayout.setHorizontalGroup(
            agregarproductopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarproductopanelLayout.createSequentialGroup()
                .addGap(6, 15, Short.MAX_VALUE)
                .addGroup(agregarproductopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Labelnombre)
                    .addComponent(Labelprecio)
                    .addComponent(labelinventario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(agregarproductopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoinventario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(agregarproductopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(camponombre, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addComponent(campoprecio)))
                .addGap(36, 36, 36))
            .addGroup(agregarproductopanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(botonagregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        agregarproductopanelLayout.setVerticalGroup(
            agregarproductopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarproductopanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(agregarproductopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labelnombre)
                    .addComponent(camponombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(agregarproductopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labelprecio)
                    .addComponent(campoprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(agregarproductopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelinventario)
                    .addComponent(campoinventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonagregar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tablaproductos.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        tablaproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Inventario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaproductos);

        botonborrar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        botonborrar.setText("Borrar ");

        botonactualizar1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        botonactualizar1.setText("Actualizar");
        botonactualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonactualizar1ActionPerformed(evt);
            }
        });

        botoninforme.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        botoninforme.setText("Generar Informe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(agregarproductopanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(bienvenidoinventarioapp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonactualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botoninforme))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bienvenidoinventarioapp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarproductopanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonborrar)
                    .addComponent(botonactualizar1)
                    .addComponent(botoninforme))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void camponombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camponombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camponombreActionPerformed

    private void botonactualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonactualizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonactualizar1ActionPerformed

    private void actnombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actnombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actnombretxtActionPerformed

    private void actbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actbotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actbotonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Actualizarframe;
    private javax.swing.JLabel Labelnombre;
    private javax.swing.JLabel Labelprecio;
    private javax.swing.JButton actboton;
    private javax.swing.JLabel actinventariolabel;
    private javax.swing.JTextField actinventariotxt;
    private javax.swing.JLabel actnombrelabel;
    private javax.swing.JTextField actnombretxt;
    private javax.swing.JLabel actpreciolabel;
    private javax.swing.JTextField actpreciotxt;
    private javax.swing.JLabel actualizarlabel;
    private javax.swing.JPanel agregarproductopanel;
    private javax.swing.JLabel bienvenidoinventarioapp;
    private javax.swing.JButton botonactualizar1;
    private javax.swing.JButton botonagregar;
    private javax.swing.JButton botonborrar;
    private javax.swing.JButton botoninforme;
    private javax.swing.JTextField campoinventario;
    private javax.swing.JTextField camponombre;
    private javax.swing.JTextField campoprecio;
    private javax.swing.JLabel descripcionlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelinventario;
    private javax.swing.JTable tablaproductos;
    // End of variables declaration//GEN-END:variables

    public JLabel getLabelnombre() {
        return Labelnombre;
    }

    public JLabel getLabelprecio() {
        return Labelprecio;
    }

    public JPanel getAgregarproductopanel() {
        return agregarproductopanel;
    }

    public JLabel getBienvenidoinventarioapp() {
        return bienvenidoinventarioapp;
    }

    public JButton getBotonactualizar1() {
        return botonactualizar1;
    }

    public JButton getBotonagregar() {
        return botonagregar;
    }

    public JButton getBotonborrar() {
        return botonborrar;
    }

    public JButton getBotoninforme() {
        return botoninforme;
    }

    public JTextField getCampoinventario() {
        return campoinventario;
    }

    public JTextField getCamponombre() {
        return camponombre;
    }

    public JTextField getCampoprecio() {
        return campoprecio;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getLabelinventario() {
        return labelinventario;
    }

    public JTable getTablaproductos() {
        return tablaproductos;
    }

    public JFrame getActualizarframe() {
        return Actualizarframe;
    }

    public JButton getActboton() {
        return actboton;
    }

    public JLabel getActinventariolabel() {
        return actinventariolabel;
    }

    public JTextField getActinventariotxt() {
        return actinventariotxt;
    }

    public JLabel getActnombrelabel() {
        return actnombrelabel;
    }

    public JTextField getActnombretxt() {
        return actnombretxt;
    }

    public JLabel getActpreciolabel() {
        return actpreciolabel;
    }

    public JTextField getActpreciotxt() {
        return actpreciotxt;
    }

    public JLabel getActualizarlabel() {
        return actualizarlabel;
    }

    public JLabel getDescripcionlabel() {
        return descripcionlabel;
    }





}
